Tickets_Project/TicketOn/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.urls import path,include
from . import views
from .views import eliminar_evento
from .views import agregar_al_carrito
from .views import quitar_del_carrito
from .views import limpiar_carrito

app_name = "TicketOn"
urlpatterns = [

    path('comprador/register/', views.register, name="register"),
    path('comprador/login/',views.my_login, name='my-login'),
    path('comprador/logout', views.user_logout, name="user-logout"),


    #Inicio
    path('', views.Home, name = 'home'),
    path('home/',views.Home,name='home'),
    path('organizador/login/', views.my_loginOrganizador, name='my_loginO'),
    path('organizador/register/', views.registerOrganizador, name='register'),


    #Comprador
    path('comprador/eventos/', views.eventos, name = 'eventos'),
    path('comprador/ayuda/',views.ayuda, name = 'ayuda'),
    path('comprador/carrito/',views.carrito, name='carrito'),
    path('comprador/eventos/<nombre_evento>/<evento_slug>',views.detalles_evento, name="detalles_evento"), #probar ejemplo /comprador/eventos/Evento%20Prueba/1

    #sistema de pagos
    path('evento/agregar_al_carrito/<slug:evento_slug>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('quitar_del_carrito/<int:ticket_id>/', quitar_del_carrito, name='quitar_del_carrito'),
    path('limpiar_carrito/', limpiar_carrito, name='limpiar_carrito'),
    path('comprador/pago_con_QR',views.pago_QR,name='pago_qr'),


    #Organizador
    path('organizador/eventos/',views.Eventos_en_curso,name='eventos_en_curso'),
    path('organizador/eventos/creacion/',views.Creacion_de_eventos, name='creacion_de_eventos'),
    path('organizador/eventos/editar/<slug:evento_slug>/', views.editar_evento, name='editar_evento'),
    path('organizador/ventas/',views.Ventas, name='ventas'),
    path('evento/eliminar/<slug:evento_slug>/', eliminar_evento, name='evento_eliminar'),

]

Tickets_Project/Tickets_Project/urls.py
from django.contrib import admin
from django.urls import path, include

# Para el manejo de archivos
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('TicketOn.urls')),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tickets_Project/TicketOn/models.py
from autoslug import AutoSlugField
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify




class Comprador(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    correo=models.CharField(max_length=30,blank=True)
    
    cvv=models.CharField(max_length=4,null=True)
    num_tarjeta=models.CharField(max_length=16,null=True)
    fecha_venc=models.DateField(null=True)
    nombre_titular=models.CharField(max_length=100,null=True)
    

    def __str__(self):
        return f"{self.usuario}"

class Organizador(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    correo=models.CharField(max_length=30,blank=True)
    empresa=models.CharField(max_length=30,blank=True)

    cuenta_clabe=models.CharField(max_length=18,null=True)
    def __str__(self):
        return f"{self.usuario}"

class Evento(models.Model):
    lugar=models.CharField(max_length=100,blank=True)
    hora=models.TimeField(blank=True)
    fecha=models.DateField()
    nombre=models.CharField(max_length=100)
    cupo=models.IntegerField()
    imagen=models.ImageField(upload_to="eventos",blank=True,null=True)
    descripcion=models.TextField(max_length=1000)
    tipo= models.CharField(max_length=20)
    organizador=models.ForeignKey(Organizador,on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from='nombre', unique=True, always_update=True)
    precio=models.FloatField(null=True)
    en_curso = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre}"
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
    

class Ticket(models.Model):
    precio = models.FloatField()
    estado = models.BooleanField(default=False)
    codigo = models.CharField(max_length=30, unique=True)
    fecha_compra = models.DateField(null=True, blank=True)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    comprador = models.ForeignKey(Comprador, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.codigo}"

class Transferencia(models.Model):
    fecha=models.DateField()
    monto_final=models.FloatField()
    estado=models.BooleanField(default=False)
    ticket=models.ForeignKey(Ticket,on_delete=models.CASCADE)
    organizador=models.ForeignKey(Organizador,on_delete=models.CASCADE)
    comprador=models.ForeignKey(Comprador,on_delete=models.CASCADE)

    
class Carrito(models.Model):
    comprador=models.ForeignKey(Comprador,on_delete=models.CASCADE)
    tickets = models.ManyToManyField(Ticket, related_name='tickets_en_carrito')

    def __str__(self):
        return f"Carrito de {self.comprador}"

Tickets_Project/TicketOn/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import *
from django.forms.widgets import PasswordInput, TextInput


TIPOS_DE_EVENTO = [
    ('concierto', 'Concierto'),
    ('conferencia', 'Conferencia'),
    ('exposicion', 'Exposición'),
    ('festival', 'Festival'),
    ('deportivo', 'Deportivo'),
    ('teatro', 'Teatro'),
    ('social', 'Social'),
    ('networking', 'Networking'),
    ('educativo', 'Educativo'),
    ('recreativo', 'Recreativo'),
    # Agrega más tipos según sea necesario
]

class CreateUserForm(UserCreationForm):

    class Meta:

        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())


class OrganizadorForm(ModelForm):
    class Meta:

        model = Organizador
        fields = ['empresa']

class EventosForm(ModelForm):
    imagen_actual = forms.ImageField(required=False, label='Imagen Actual', disabled=True)
    class Meta:

        model = Evento
        fields = ['nombre', 'descripcion', 'lugar', 'fecha', 'hora', 'tipo', 'cupo', 'precio', 'imagen'] 
        widgets = {
            'imagen': forms.ClearableFileInput(),
            'fecha': forms.DateInput(attrs={'type': 'date'}),
            'hora': forms.TimeInput(attrs={'type': 'time'}),
            'precio': forms.NumberInput(attrs={'min': '0.00', 'step': '0.01'}),
            'cupo': forms.NumberInput(attrs={'min': '0', 'step': '0'}),
            'tipo': forms.Select(choices=TIPOS_DE_EVENTO),
            'descripcion': forms.Textarea(attrs={'cols': 51, 'rows': 10}), 
        }     
        

Tickets_Project/TicketOn/views.py
from typing import Self
from functools import wraps
from django.http import HttpResponse,JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from .forms import *
from .models import *
from django.contrib.auth.models import auth
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate, login, logout
from allauth.account.decorators import login_required
import random
import string
from copy import deepcopy
from datetime import date
from django.contrib import messages
import requests
import qrcode
from Tickets_Project.settings import MEDIA_ROOT

#Sesión comprador
def register(request):
    auth.logout(request)
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)

        if form.is_valid():
            user = form.save()
            email = user.email
            Comprador.objects.create(usuario=user,correo=email)
            return redirect("TicketOn:my-login")

    context = {'registerform': form}
    return render(request, 'Inicio/comprador_register.html', context=context)
    
def my_login(request):
    auth.logout(request)
    form = LoginForm()

    if request.method == 'POST':

        form = LoginForm(request, data=request.POST)

        if form.is_valid():

            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:

                auth.login(request, user)

                return redirect("TicketOn:eventos")


    context = {'loginform':form}

    return render(request, 'Inicio/comprador_login.html', context=context)






#Sesión Organizador
def registerOrganizador(request):
    auth.logout(request)
    user_form = CreateUserForm()
    organizador_form = OrganizadorForm()

    if request.method == "POST":
        user_form = CreateUserForm(request.POST)
        organizador_form = OrganizadorForm(request.POST)

        if user_form.is_valid() and organizador_form.is_valid():
            user = user_form.save()
            email = user.email
            empresa = organizador_form.cleaned_data['empresa']
            Organizador.objects.create(usuario=user, correo=email, empresa=empresa)
            return redirect("TicketOn:my_loginO")

    context = {'registerform': user_form, 'OrganizadorForm': organizador_form}
    return render(request, 'Inicio/organizador_register.html', context=context)
    
def my_loginOrganizador(request):
    auth.logout(request)
    form = LoginForm()

    if request.method == 'POST':

        form = LoginForm(request, data=request.POST)

        if form.is_valid():

            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:

                auth.login(request, user)

                return redirect("TicketOn:eventos_en_curso")


    context = {'loginform':form}

    return render(request, 'Inicio/organizador_login.html', context=context)



def user_logout(request):

    auth.logout(request)

    return redirect("/home/")


def comprador_required(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        # Verifica si el usuario actual es un comprador
        if request.user.is_authenticated and Comprador.objects.filter(usuario=request.user).exists():
            return view_func(request, *args, **kwargs)
        else:
            return redirect("TicketOn:my-login")  # Redirige a la página de inicio de sesión si no es un comprador
    return _wrapped_view

def Organizador_required(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        # Verifica si el usuario actual es un comprador
        if request.user.is_authenticated and Organizador.objects.filter(usuario=request.user).exists():
            return view_func(request, *args, **kwargs)
        else:
            return redirect("TicketOn:my_loginO")  # Redirige a la página de inicio de sesión si no es un organizador
    return _wrapped_view


# Inicio
def Home(request):
    return render(request, 'Inicio/Home.html')

def comprador_login(request):
    return render(request, 'Inicio/comprador_login.html')

def organizador_login(request):
    return render(request, 'Inicio/organizador_login.html')

def comprador_register(request):
    return render(request, 'Inicio/comprador_register.html')

def organizador_register(request):
    return render(request, 'Inicio/organizador_register.html')

#Comprador
@comprador_required
def eventos(request):
    if request.method =="GET":
        eventos = Evento.objects.all()
        return render (request,'Comprador/Eventos.html',{
            'eventos':eventos
        })
    else:
        nombre_busq = request.POST["nombre"]
        tipo_busq = request.POST["tipo"]
        lugar_busq = request.POST["lugar"]
        fecha_busq = request.POST["fecha"]
        
        if not fecha_busq:
            eventos = Evento.objects.filter(nombre__contains = nombre_busq,tipo__contains = tipo_busq, lugar__contains = lugar_busq)
            
        else:
            eventos = Evento.objects.filter(nombre__contains = nombre_busq,tipo__contains = tipo_busq, lugar__contains = lugar_busq,fecha = fecha_busq)
        
        return render (request,'Comprador/Eventos.html',{
            'eventos':eventos,
            'nombre_busq': nombre_busq,
            'tipo_busq': tipo_busq,
            'fecha_busq': fecha_busq,
            'lugar_busq':lugar_busq
        })
    
    
    

@comprador_required
def ayuda(request):
    return render (request,'Comprador/Ayuda.html')

@comprador_required
def carrito(request):
    # Obtener el carrito del comprador actual
    comprador_actual = Comprador.objects.get(usuario=request.user)
    carrito, creado = Carrito.objects.get_or_create(comprador=comprador_actual)

    # Obtener todos los tickets en el carrito
    tickets_en_carrito = carrito.tickets.all()
    montofinal = sum(ticket.precio for ticket in tickets_en_carrito)
    

    return render(request, 'Comprador/Carrito.html', {'tickets_en_carrito': tickets_en_carrito, 'montofinal': montofinal})

@comprador_required
def detalles_evento(request,nombre_evento,evento_slug):
    evento= Evento.objects.get(slug=evento_slug)
    return render(request,'Comprador/Detalles_Evento.html',{
        "evento":evento
    })



#Organizador
@Organizador_required
def Eventos_en_curso(request):
    organizador = get_object_or_404(Organizador, usuario=request.user)
    eventos_en_curso = Evento.objects.filter(organizador=organizador,en_curso=True)
    return render(request, 'Organizador/Eventos_en_curso.html', {'eventos_en_curso': eventos_en_curso})

@Organizador_required
def Creacion_de_eventos(request):
    evento_form = EventosForm()

    if request.method == "POST":
        evento_form = EventosForm(request.POST, request.FILES)

        if evento_form.is_valid():
            organizador = Organizador.objects.get(usuario=request.user)
            
            nuevo_evento = evento_form.save(commit=False)
            
            nuevo_evento.organizador = organizador

            nuevo_evento.save()

            return redirect("TicketOn:eventos_en_curso")

    context = {'Evento_form': evento_form}
    return render(request, 'Organizador/Creacion_de_eventos.html', context=context)

@Organizador_required
def Ventas(request):
    return render(request, 'Organizador/Ventas.html')


@Organizador_required
def editar_evento(request, evento_slug):
    evento = get_object_or_404(Evento, slug=evento_slug)

    if request.user != evento.organizador.usuario:
        return redirect("TicketOn:eventos_en_curso")

    if request.method == 'POST':
        if 'eliminar_evento' in request.POST:
            evento.delete()
            return redirect("TicketOn:eventos_en_curso")

        evento_form = EventosForm(request.POST, request.FILES, instance=evento)
        if evento_form.is_valid():
            evento_form.save()
            return redirect("TicketOn:eventos_en_curso")
    else:
        evento_form = EventosForm(instance=evento)

    return render(request, 'Organizador/Editar_eventos.html', {'Evento_form': evento_form, 'evento': evento})

def eliminar_evento(request, evento_slug):
    evento = get_object_or_404(Evento, slug=evento_slug)

    if request.method == 'POST' and 'eliminar_evento' in request.POST:
        evento.delete()
        return redirect("TicketOn:eventos_en_curso")

    return render(request, 'ruta_a_tu_plantilla_eliminar_evento.html', {'evento': evento})

#Sistema logico de tickets
def generar_codigo():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))


#Sistema de pagos
def agregar_al_carrito(request, evento_slug):
    evento = get_object_or_404(Evento, slug=evento_slug)

    if request.method == 'POST':
        cantidad = request.POST.get('cant_tickets', 1)

        try:
            cantidad = int(cantidad)
            comprador_actual = Comprador.objects.get(usuario=request.user)

            carrito, creado = Carrito.objects.get_or_create(comprador=comprador_actual)

            for _ in range(cantidad):
                codigo_ticket = generar_codigo()

                while Ticket.objects.filter(codigo=codigo_ticket).exists():
                    codigo_ticket = generar_codigo()

                nuevo_ticket = Ticket.objects.create(
                    precio=evento.precio,
                    estado=False,
                    codigo=codigo_ticket,
                    fecha_compra=None,

Tickets_Project/TicketOn/templates/Comprador/Ayuda.html
{% extends 'Conex/Conex_comprador.html' %} {% block content %} {%load static%}
<link rel="stylesheet" href="{% static 'TicketOn/Comprador.css'%}" />
<style>
    h1{
        font-size: 80px;
        font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
        margin:50px;
        margin-top: 150px;
        color:#000;
    }

    .titulo-seccion{
        font-size: 50px;
    }

    p{
        color:white;
        margin:20px 40px;
        font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
        font-size: 30px;
    }

   #QS{
    text-align:justify;
    text-justify:inter-word;
    display:flex;
    background-color: #235391;
    width: 90%;
    margin: auto;
    height: fit-content;
    justify-content:space-between;
   }

   #QS img{
    width:250px;
    height:auto;
    margin:50px;
   }

   #PF{
    text-align:justify;
    text-justify:inter-word;
    padding-bottom:40px;
    background-color: #193C69;
    width: 90%;
    margin: auto;
   }

   #CT{
    background-color: #0F2440;
    text-align:justify;
    text-justify:inter-word;
    padding-bottom:20px;
    width: 90%;
    margin: auto;
    margin-bottom: 150px;
   }
</style>
<h1>AYUDA</h1>

<div id="QS">
    <div id="info">
        <h2 class="titulo-seccion">¿Quienes somos?</h2>
        <p>TicketJaeger es una nueva opcion para todo aquel que busque boletos para sus eventos favoritos, esta diseñado para 
            ser facil de entender y navegar, esperamos que TicketJaeger te sea util para crear y organizar tus eventos; o que te sirva para 
            encontrar los eventos que buscas de manera sencilla. Jaeger significa cazador en aleman, y asi como un cazador puedes usar TicketJaeger para 
            cazar los evento que quieres.
        </p>
    </div>
    
    <img id="logo" src={%static 'TicketOn/image/Icon.png '%} alt="Logo de
      TicketJaeger" />
</div>
<br>
<div id="PF">
    <h2 class="titulo-seccion">Preguntas frecuentes</h2>
    <p>
        ¿Cuesta hacer una cuenta en TicketJaeger?<br>
        -No, registrarse como usuario es completamente gratis<br>
        <br>
        ¿Cual es la diferencia entre una cuenta de comprador y una de organizador?<br>
        -Segun el tipo de usuario se pueden hacer distintas acciones, los compradores pueden buscar entre los 
        eventos disponilbles para escoger boletos, agregarlos a su carrito y comprarlos<br>
        <br>
        ¿Podemos esperar mas de TicketJaeger?<br>
        -Si, el sistema esta en sus primeros dias de desarrollo y estamos trabajando para traer mayor funcionalidad
        de la manera mas eficiente posible<br>
        <br>
    </p>
</div>
<br>
<div id="CT">
    <h2 class="titulo-seccion">Contactanos</h2>
    <p>
        -Telefono de atencion: 656-495-88-83<br>
        -Correo de atencion: TicketJaeger@ayuda.com<br>
        -Instagaram: @TicketJaeger<br>
        -Facebook: TicketJaeger<br>
    </p>
</div>
<footer>
    <p href="/home/">TicketJaeger</p>
    <ul>
        <li>Telefono de atencion: 656-495-88-83<br></li>
        <li>Correo de atencion: TicketJaeger@ayuda.com<br></li>
        <li>Instagaram: @TicketJaeger<br></li>
        <li>Facebook: TicketJaeger<br></li>
    </ul>
</footer>

{% endblock %}

Tickets_Project/TicketOn/templates/Comprador/Carrito.html
{% extends 'Conex/Conex_comprador.html' %} {% block content %} {% load static %}

<link rel="stylesheet" href="{% static 'TicketOn/Carrito.css' %}" />

<h1>Tu carrito</h1>

<!-- Replace "test" with your own sandbox Business account app client ID -->
<script src="https://www.paypal.com/sdk/js?client-id=AQDWQ5DHWzCXGvoh6tCdBLxAA2cPONYAr0Bn7Z5I8J0nbHBRDOc1FPLfjxDZ5A7KdN6C4tnDvY783A25"></script>

<div id="Carrito">
    {% if tickets_en_carrito %}
        {% for ticket in tickets_en_carrito %}
        <div class="tarjeta_ticket">
            {% if ticket.evento.imagen %}
                <img src="{{ ticket.evento.imagen.url }}" class="evento-img"></img>
            {% else %}
                <img src="{% static 'TicketOn/image/default_event_image.jpg' %}" class="evento-img"></img>
            {% endif %}
            
            <div id="info_ticket">
                <div >
                    <h2>{{ ticket.evento.nombre }}</h2>
                    <h3> ${{ ticket.precio }} - ID: {{ ticket.codigo }}</h3>
                    <h3>{{ ticket.evento.fecha }} - {{ ticket.evento.hora}} - {{ ticket.evento.lugar }}</h3>
                </div>
            </div>
            <div id="Botones">
                <form action="{% url 'TicketOn:detalles_evento' ticket.evento.nombre ticket.evento.slug%}">
                    <input type="submit" value="Ver evento" />
                </form>
                <form method="POST" action="{% url 'TicketOn:quitar_del_carrito' ticket.id %}" >
                    {% csrf_token %}
                    <button type="submit">Quitar</button>
                </form>
            </div>
        </div>
        {% endfor %}

    {% else %}
        <div id="tarjeta_ticket">
            <div id="info_ticket">
                <h2>El carrito está vacío.</h2>
            </div>
        </div>
        
    {% endif %} 
    
</div>
<div id="Div-Total">
    <div id="GB_Botones">
        <form action="{% url 'TicketOn:eventos'%}">
            <input type="submit" value="Seguir buscando" />
        </form>
        <form method="POST"  action="{% url 'TicketOn:limpiar_carrito' %}" >
            {% csrf_token %}
            <button type="submit">Limpiar carrito</button>
        </form>
        <form method="POST"  action="{% url 'TicketOn:pago_qr' %}" >
            {% csrf_token %}
            <button type="submit">Pagar con QR</button>
        </form>
    </div>
    <div id="Div-montofinal">
        <h2>Monto Total: ${{ montofinal }}</h2>
        
        <!-- Set up a container element for the button -->
        <div id="paypal-button-container"></div>
        <script montofinal="{{montofinal}}">
            paypal.Buttons({
                createOrder: function(data,actions){
                    return actions.order.create({
                        purchase_units:[{
                            amount:{
                                value:{{montofinal}}
                            }
                        }]
                    });
            },
            onApprove: function(data,acrtions){
                return actions.order.capture().then(function(details){
                    alert('Transaction completed by '+ details.payer.name.given_name);
                });
            }
            }).render('#paypal-button-container');
        </script>
    </div>
</div>
<br><br>
<footer>
    <p href="/home/">TicketJaeger</p>
    <ul>
        <li>Telefono de atencion: 656-495-88-83<br></li>
        <li>Correo de atencion: TicketJaeger@ayuda.com<br></li>
        <li>Instagaram: @TicketJaeger<br></li>
        <li>Facebook: TicketJaeger<br></li>
    </ul>
</footer>


<!--<link rel="stylesheet" href="{% static 'TicketOn/Comprador.css' %}" />

<style>
  .quitarticket {
    background-color: #ff0000;
    color: #fff;
    font-size: 20px;
    border-radius: 4px;
    cursor: pointer;
    width: 200px;
    box-sizing: border-box;
  }
</style>

<h1>Carrito</h1>

{% if tickets_en_carrito %}
<ul>
  {% for ticket in tickets_en_carrito %}
  <a>
    Nombre: {{ ticket.evento.nombre }} - Precio: ${{ ticket.precio }} - ID:
    {{ticket.codigo}}
  </a>
  <form
    method="post"
    action="{% url 'TicketOn:quitar_del_carrito' ticket.id %}"
  >
    {% csrf_token %}
    <button class="quitarticket" type="submit">Quitar del carrito</button>
  </form>
  {% endfor %}
</ul>
<p>Monto Total: ${{ montofinal }}</p>

{% else %}
<a>El carrito está vacío.</a>
{% endif %} {% endblock %}-->

Tickets_Project/TicketOn/templates/Comprador/Detalles_Evento.html
{% extends "Conex/Conex_comprador.html" %} {%block content%} {%load static%}

<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {%load static%}
        <link rel="stylesheet" href="{% static 'TicketOn/Comprador.css'%}" />
        <title>TicketJaeger - {{evento.nombre}}</title>

    </head>
    <body>
        <br>
        <div id="Seccion_1">
            {% if evento.imagen %}
                <img src="{{ evento.imagen.url }}" class="evento-img"></img>
            {% else %}
                <img src="{% static 'TicketOn/image/default_event_image.jpg' %}" class="evento-img"></img>
            {% endif %}
            <div id="Seccion_1_Info">
                <h2 id="nombre_evento">{{evento.nombre}}</h2>
                <p>{{evento.descripcion}}<p>
            </div>
        </div>
        <div id="Seccion_2">
            <div id="Seccion_2_Info">
                <p>Oprganizador: {{evento.organizador}} - Precio: $ {{evento.precio}} </p>
                <p>Ubicacion: {{evento.lugar}} - Cupos disponibles: {{evento.cupo}}</p>
                <p>Fecha: {{evento.fecha}}  - Hora: {{evento.hora}} </p>
            </div>
            <div id="Seccion_Agregar">
                <form method="POST" action="{% url 'TicketOn:agregar_al_carrito' evento.slug %}">
                    {% csrf_token %}
                    <label for="cant_tickets">Cantidad de boletos:</label>
                    <input id="cant" type="number" id="cant_tickets" name="cant_tickets" min="1"><br><br>
                    <input id="btn" type="submit" value="Agregar al carrito">
                </form>
            </div>
        </div>
        <footer>
            <p href="/home/">TicketJaeger</p>
            <ul>
                <li>Telefono de atencion: 656-495-88-83<br></li>
                <li>Correo de atencion: TicketJaeger@ayuda.com<br></li>
                <li>Instagaram: @TicketJaeger<br></li>
                <li>Facebook: TicketJaeger<br></li>
            </ul>
        </footer>
    </body>
    {%endblock%}
</html>

Tickets_Project/TicketOn/templates/Comprador/Pago_QR.html
{% extends "Conex/Conex_comprador.html" %} {%block content%} {%load static%}

<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {%load static%}
        <link rel="stylesheet" href="{% static 'TicketOn/Comprador.css'%}" />
        <title>TicketJaeger -</title>

    </head>
    <style>
        #qr{
            width:50%;
            margin:auto;
            margin-top:200px;
            padding:50px;
        }

        #qr img{
            margin:auto;
            width:600px;
            height: 600px;
        }

        #QRmensaje{
            font-size:30px;
            color:#000;
        }

    </style>
    <body>
       <div id="qr">
        <img src="{{img}}">
        <h2 id="QRmensaje">Aqui puedes pagar tu carrito</h2>
       </div>
       
    </body>
    
    {%endblock%}
</html>