Tickets_Project/TicketOn/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.urls import path,include
from . import views
from .views import eliminar_evento
from .views import agregar_al_carrito
from .views import quitar_del_carrito
from .views import limpiar_carrito

app_name = "TicketOn"
urlpatterns = [

    path('comprador/register/', views.register, name="register"),
    path('comprador/login/',views.my_login, name='my-login'),
    path('comprador/logout', views.user_logout, name="user-logout"),


    #Inicio
    path('', views.Home, name = 'home'),
    path('home/',views.Home,name='home'),
    path('organizador/login/', views.my_loginOrganizador, name='my_loginO'),
    path('organizador/register/', views.registerOrganizador, name='register'),


    #Comprador
    path('comprador/eventos/', views.eventos, name = 'eventos'),
    path('comprador/ayuda/',views.ayuda, name = 'ayuda'),
    path('comprador/carrito/',views.carrito, name='carrito'),
    path('comprador/eventos/<nombre_evento>/<evento_slug>',views.detalles_evento, name="detalles_evento"), #probar ejemplo /comprador/eventos/Evento%20Prueba/1

    #sistema de pagos
    path('evento/agregar_al_carrito/<slug:evento_slug>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('quitar_del_carrito/<int:ticket_id>/', quitar_del_carrito, name='quitar_del_carrito'),
    path('limpiar_carrito/', limpiar_carrito, name='limpiar_carrito'),
    path('comprador/pago_con_QR',views.pago_QR,name='pago_qr'),


    #Organizador
    path('organizador/eventos/',views.Eventos_en_curso,name='eventos_en_curso'),
    path('organizador/eventos/creacion/',views.Creacion_de_eventos, name='creacion_de_eventos'),
    path('organizador/eventos/editar/<slug:evento_slug>/', views.editar_evento, name='editar_evento'),
    path('organizador/ventas/',views.Ventas, name='ventas'),
    path('evento/eliminar/<slug:evento_slug>/', eliminar_evento, name='evento_eliminar'),

]

Tickets_Project/Tickets_Project/urls.py
from django.contrib import admin
from django.urls import path, include

# Para el manejo de archivos
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('TicketOn.urls')),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tickets_Project/TicketOn/models.py
from autoslug import AutoSlugField
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify




class Comprador(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    correo=models.CharField(max_length=30,blank=True)
    
    cvv=models.CharField(max_length=4,null=True)
    num_tarjeta=models.CharField(max_length=16,null=True)
    fecha_venc=models.DateField(null=True)
    nombre_titular=models.CharField(max_length=100,null=True)
    

    def __str__(self):
        return f"{self.usuario}"

class Organizador(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    correo=models.CharField(max_length=30,blank=True)
    empresa=models.CharField(max_length=30,blank=True)

    cuenta_clabe=models.CharField(max_length=18,null=True)
    def __str__(self):
        return f"{self.usuario}"

class Evento(models.Model):
    lugar=models.CharField(max_length=100,blank=True)
    hora=models.TimeField(blank=True)
    fecha=models.DateField()
    nombre=models.CharField(max_length=100)
    cupo=models.IntegerField()
    imagen=models.ImageField(upload_to="eventos",blank=True,null=True)
    descripcion=models.TextField(max_length=1000)
    tipo= models.CharField(max_length=20)
    organizador=models.ForeignKey(Organizador,on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from='nombre', unique=True, always_update=True)
    precio=models.FloatField(null=True)
    en_curso = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre}"
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
    

class Ticket(models.Model):
    precio = models.FloatField()
    estado = models.BooleanField(default=False)
    codigo = models.CharField(max_length=30, unique=True)
    fecha_compra = models.DateField(null=True, blank=True)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    comprador = models.ForeignKey(Comprador, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.codigo}"

class Transferencia(models.Model):
    fecha=models.DateField()
    monto_final=models.FloatField()
    estado=models.BooleanField(default=False)
    ticket=models.ForeignKey(Ticket,on_delete=models.CASCADE)
    organizador=models.ForeignKey(Organizador,on_delete=models.CASCADE)
    comprador=models.ForeignKey(Comprador,on_delete=models.CASCADE)

    
class Carrito(models.Model):
    comprador=models.ForeignKey(Comprador,on_delete=models.CASCADE)
    tickets = models.ManyToManyField(Ticket, related_name='tickets_en_carrito')

    def __str__(self):
        return f"Carrito de {self.comprador}"

Tickets_Project/TicketOn/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import *
from django.forms.widgets import PasswordInput, TextInput


TIPOS_DE_EVENTO = [
    ('concierto', 'Concierto'),
    ('conferencia', 'Conferencia'),
    ('exposicion', 'Exposición'),
    ('festival', 'Festival'),
    ('deportivo', 'Deportivo'),
    ('teatro', 'Teatro'),
    ('social', 'Social'),
    ('networking', 'Networking'),
    ('educativo', 'Educativo'),
    ('recreativo', 'Recreativo'),
    # Agrega más tipos según sea necesario
]

class CreateUserForm(UserCreationForm):

    class Meta:

        model = User
        fields = ['username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())


class OrganizadorForm(ModelForm):
    class Meta:

        model = Organizador
        fields = ['empresa']

class EventosForm(ModelForm):
    imagen_actual = forms.ImageField(required=False, label='Imagen Actual', disabled=True)
    class Meta:

        model = Evento
        fields = ['nombre', 'descripcion', 'lugar', 'fecha', 'hora', 'tipo', 'cupo', 'precio', 'imagen'] 
        widgets = {
            'imagen': forms.ClearableFileInput(),
            'fecha': forms.DateInput(attrs={'type': 'date'}),
            'hora': forms.TimeInput(attrs={'type': 'time'}),
            'precio': forms.NumberInput(attrs={'min': '0.00', 'step': '0.01'}),
            'cupo': forms.NumberInput(attrs={'min': '0', 'step': '0'}),
            'tipo': forms.Select(choices=TIPOS_DE_EVENTO),
            'descripcion': forms.Textarea(attrs={'cols': 51, 'rows': 10}), 
        }     
        

Tickets_Project/TicketOn/views.py
from typing import Self
from functools import wraps
from django.http import HttpResponse,JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from .forms import *
from .models import *
from django.contrib.auth.models import auth
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate, login, logout
from allauth.account.decorators import login_required
import random
import string
from copy import deepcopy
from datetime import date
from django.contrib import messages
import requests
import qrcode
from Tickets_Project.settings import MEDIA_ROOT

#Sesión comprador
def register(request):
    auth.logout(request)
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)

        if form.is_valid():
            user = form.save()
            email = user.email
            Comprador.objects.create(usuario=user,correo=email)
            return redirect("TicketOn:my-login")

    context = {'registerform': form}
    return render(request, 'Inicio/comprador_register.html', context=context)
    
def my_login(request):
    auth.logout(request)
    form = LoginForm()

    if request.method == 'POST':

        form = LoginForm(request, data=request.POST)

        if form.is_valid():

            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:

                auth.login(request, user)

                return redirect("TicketOn:eventos")


    context = {'loginform':form}

    return render(request, 'Inicio/comprador_login.html', context=context)






#Sesión Organizador
def registerOrganizador(request):
    auth.logout(request)
    user_form = CreateUserForm()
    organizador_form = OrganizadorForm()

    if request.method == "POST":
        user_form = CreateUserForm(request.POST)
        organizador_form = OrganizadorForm(request.POST)

        if user_form.is_valid() and organizador_form.is_valid():
            user = user_form.save()
            email = user.email
            empresa = organizador_form.cleaned_data['empresa']
            Organizador.objects.create(usuario=user, correo=email, empresa=empresa)
            return redirect("TicketOn:my_loginO")

    context = {'registerform': user_form, 'OrganizadorForm': organizador_form}
    return render(request, 'Inicio/organizador_register.html', context=context)
    
def my_loginOrganizador(request):
    auth.logout(request)
    form = LoginForm()

    if request.method == 'POST':

        form = LoginForm(request, data=request.POST)

        if form.is_valid():

            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:

                auth.login(request, user)

                return redirect("TicketOn:eventos_en_curso")


    context = {'loginform':form}

    return render(request, 'Inicio/organizador_login.html', context=context)



def user_logout(request):

    auth.logout(request)

    return redirect("/home/")


def comprador_required(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        # Verifica si el usuario actual es un comprador
        if request.user.is_authenticated and Comprador.objects.filter(usuario=request.user).exists():
            return view_func(request, *args, **kwargs)
        else:
            return redirect("TicketOn:my-login")  # Redirige a la página de inicio de sesión si no es un comprador
    return _wrapped_view

def Organizador_required(view_func):
    @wraps(view_func)
    def _wrapped_view(request, *args, **kwargs):
        # Verifica si el usuario actual es un comprador
        if request.user.is_authenticated and Organizador.objects.filter(usuario=request.user).exists():
            return view_func(request, *args, **kwargs)
        else:
            return redirect("TicketOn:my_loginO")  # Redirige a la página de inicio de sesión si no es un organizador
    return _wrapped_view


# Inicio
def Home(request):
    return render(request, 'Inicio/Home.html')

def comprador_login(request):
    return render(request, 'Inicio/comprador_login.html')

def organizador_login(request):
    return render(request, 'Inicio/organizador_login.html')

def comprador_register(request):
    return render(request, 'Inicio/comprador_register.html')

def organizador_register(request):
    return render(request, 'Inicio/organizador_register.html')

#Comprador
@comprador_required
def eventos(request):
    if request.method =="GET":
        eventos = Evento.objects.all()
        return render (request,'Comprador/Eventos.html',{
            'eventos':eventos
        })
    else:
        nombre_busq = request.POST["nombre"]
        tipo_busq = request.POST["tipo"]
        lugar_busq = request.POST["lugar"]
        fecha_busq = request.POST["fecha"]
        
        if not fecha_busq:
            eventos = Evento.objects.filter(nombre__contains = nombre_busq,tipo__contains = tipo_busq, lugar__contains = lugar_busq)
            
        else:
            eventos = Evento.objects.filter(nombre__contains = nombre_busq,tipo__contains = tipo_busq, lugar__contains = lugar_busq,fecha = fecha_busq)
        
        return render (request,'Comprador/Eventos.html',{
            'eventos':eventos,
            'nombre_busq': nombre_busq,
            'tipo_busq': tipo_busq,
            'fecha_busq': fecha_busq,
            'lugar_busq':lugar_busq
        })
    
    
    

@comprador_required
def ayuda(request):
    return render (request,'Comprador/Ayuda.html')

@comprador_required
def carrito(request):
    # Obtener el carrito del comprador actual
    comprador_actual = Comprador.objects.get(usuario=request.user)
    carrito, creado = Carrito.objects.get_or_create(comprador=comprador_actual)

    # Obtener todos los tickets en el carrito
    tickets_en_carrito = carrito.tickets.all()
    montofinal = sum(ticket.precio for ticket in tickets_en_carrito)
    

    return render(request, 'Comprador/Carrito.html', {'tickets_en_carrito': tickets_en_carrito, 'montofinal': montofinal})

@comprador_required
def detalles_evento(request,nombre_evento,evento_slug):
    evento= Evento.objects.get(slug=evento_slug)
    return render(request,'Comprador/Detalles_Evento.html',{
        "evento":evento
    })



#Organizador
@Organizador_required
def Eventos_en_curso(request):
    organizador = get_object_or_404(Organizador, usuario=request.user)
    eventos_en_curso = Evento.objects.filter(organizador=organizador,en_curso=True)
    return render(request, 'Organizador/Eventos_en_curso.html', {'eventos_en_curso': eventos_en_curso})

@Organizador_required
def Creacion_de_eventos(request):
    evento_form = EventosForm()

    if request.method == "POST":
        evento_form = EventosForm(request.POST, request.FILES)

        if evento_form.is_valid():
            organizador = Organizador.objects.get(usuario=request.user)
            
            nuevo_evento = evento_form.save(commit=False)
            
            nuevo_evento.organizador = organizador

            nuevo_evento.save()

            return redirect("TicketOn:eventos_en_curso")

    context = {'Evento_form': evento_form}
    return render(request, 'Organizador/Creacion_de_eventos.html', context=context)

@Organizador_required
def Ventas(request):
    return render(request, 'Organizador/Ventas.html')


@Organizador_required
def editar_evento(request, evento_slug):
    evento = get_object_or_404(Evento, slug=evento_slug)

    if request.user != evento.organizador.usuario:
        return redirect("TicketOn:eventos_en_curso")

    if request.method == 'POST':
        if 'eliminar_evento' in request.POST:
            evento.delete()
            return redirect("TicketOn:eventos_en_curso")

        evento_form = EventosForm(request.POST, request.FILES, instance=evento)
        if evento_form.is_valid():
            evento_form.save()
            return redirect("TicketOn:eventos_en_curso")
    else:
        evento_form = EventosForm(instance=evento)

    return render(request, 'Organizador/Editar_eventos.html', {'Evento_form': evento_form, 'evento': evento})

def eliminar_evento(request, evento_slug):
    evento = get_object_or_404(Evento, slug=evento_slug)

    if request.method == 'POST' and 'eliminar_evento' in request.POST:
        evento.delete()
        return redirect("TicketOn:eventos_en_curso")

    return render(request, 'ruta_a_tu_plantilla_eliminar_evento.html', {'evento': evento})

#Sistema logico de tickets
def generar_codigo():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))


#Sistema de pagos
def agregar_al_carrito(request, evento_slug):
    evento = get_object_or_404(Evento, slug=evento_slug)

    if request.method == 'POST':
        cantidad = request.POST.get('cant_tickets', 1)

        try:
            cantidad = int(cantidad)
            comprador_actual = Comprador.objects.get(usuario=request.user)

            carrito, creado = Carrito.objects.get_or_create(comprador=comprador_actual)

            for _ in range(cantidad):
                codigo_ticket = generar_codigo()

                while Ticket.objects.filter(codigo=codigo_ticket).exists():
                    codigo_ticket = generar_codigo()

                nuevo_ticket = Ticket.objects.create(
                    precio=evento.precio,
                    estado=False,
                    codigo=codigo_ticket,
                    fecha_compra=None,

Tickets_Project/TicketOn/templates/Organizador/Editar_eventos.html
{% extends 'Conex/Conex_organizador.html' %} {% block content %} {%load static%}
<link rel="stylesheet" href="{% static 'TicketOn/Organizador.css'%}" />
<style>

#main-nav_1 a:hover{
  font-size: 28px;
  color:#000;
  opacity: 50%;
}
#main-nav_1:hover {
    box-shadow: 0px 10px 25px #00000043;
    height: 70px;
    padding-top: 20px;
  }

#main-nav_1 {
    display: flex;
    padding: 5px 5%;
    justify-content: space-between;
    box-shadow: 0px 10px 25px #00000043;
    background-color: #93c012;
    height: 60px;
    top: 0;
    position: fixed;
    width: 100%;
    transition-duration: 0.3s;
  }

  #imagenevento {
    display: block;
    margin-top: 15px;
    width: 400px;
    height: 300px;
    margin-left: auto;
    margin-right: auto;
  }

  #container {
    margin-top: 100px;
    text-align: center;
    position: relative;
  }

  #container2 {
    text-align: center;
    position: relative; 
  }

  .reptido::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: url('{% static "TicketOn/image/Icon.png" %}') repeat;
    background-size: 5.5%;
    opacity: 0.15;
    z-index: -1; 
}

  form {
    background-color: #fff;
    margin-bottom: 20px;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    max-width: 400px;
    width: 100%;
    display: inline-block;
    text-align: left;
  }

  h1 {
    color: #fff;
  }

  h2 {
    margin-top: 10px;
    color: #333;
    justify-content: center;
    text-align: center;
  }

  label {
    margin-top: 3px;
    width: 100%;
    font-weight: bold;
    display: block;
  }

  input {
    width: 100%;
    padding: 8px;
    margin-bottom: 10px;
    box-sizing: border-box;
  }

  input[type="submit"] {
    background-color: #4caf50;
    color: #fff;
    border: none;
    padding: 10px 15px;
    font-size: 16px;
    border-radius: 4px;
    cursor: pointer;
    margin-top: 10px;
  }

  input[type="submit"]:hover {
    background-color: #45a049;
    font-size: 25px;
    color: #000000;
  }

  button {
    background-color: #ff0000;
    color: #fff;
    border: none;
    padding: 10px 15px;
    font-size: 16px;
    border-radius: 4px;
    cursor: pointer;
    margin-top: 10px;
    width: 100%;
    padding: 8px;
    margin-bottom: 10px;
    box-sizing: border-box;
  }

  button:hover {
    background-color: #901616;
    font-size: 25px;
    color: #000000;
  }

  #imagen-previa {
    max-width: 100%;
    height: auto;
    margin-top: 10px;
  }

  img {
    display: block;
    width: 400px;
    height: auto;
  }
</style>

<div id="container">
  <h1>Editar evento</h1>
  <form method="POST" autocomplete="off" enctype="multipart/form-data">
    {% csrf_token %}
    <h2>{{ evento.nombre }}</h2>
    <div>
      {% if evento.imagen %}
      <img src="{{ evento.imagen.url }}" alt="{{ evento.nombre }}" />
      {% endif %}
    </div>

    <label for="{{ Evento_form.nombre.id_for_label }}">Nombre:</label>
    {{ Evento_form.nombre }}

    <label for="{{ Evento_form.descripcion.id_for_label }}">Descripción:</label>
    {{ Evento_form.descripcion }}

    <label for="{{ Evento_form.lugar.id_for_label }}">Lugar:</label>
    {{ Evento_form.lugar }}

    <label for="{{ Evento_form.fecha.id_for_label }}">Fecha:</label>
    {{ Evento_form.fecha }}

    <label for="{{ Evento_form.hora.id_for_label }}">Hora:</label>
    {{ Evento_form.hora }}

    <label for="{{ Evento_form.tipo.id_for_label }}">Tipo:</label>
    {{ Evento_form.tipo }}

    <label for="{{ Evento_form.cupo.id_for_label }}">Cupo:</label>
    {{ Evento_form.cupo }}

    <label for="{{ Evento_form.precio.id_for_label }}">Precio:</label>
    {{ Evento_form.precio }}

    <label for="{{ Evento_form.imagen.id_for_label }}">Imagen:</label>
    <input
      type="file"
      name="imagen"
      id="imagen-input"
      accept="image/*"
      onchange="mostrarVistaPrevia(this)"
    />
    <img id="imagen-previa" style="display: none" />
    <input type="submit" value="Guardar Cambios" />
  </form>

  <div class="reptido"></div>
</div>

<div id="container2">
  <form method="POST" action="{% url 'TicketOn:evento_eliminar' evento.slug %}">
    {% csrf_token %}
    <input type="hidden" name="eliminar_evento" value="true" />
    <button type="submit">Eliminar evento</button>
  </form>
  <div class="reptido"></div>
</div>

<script>
  function mostrarVistaPrevia(input) {
    var vistaPrevia = document.getElementById("imagen-previa");
    var archivo = input.files[0];

    if (archivo) {
      var lector = new FileReader();

      lector.onload = function (e) {
        vistaPrevia.src = e.target.result;
        vistaPrevia.style.display = "block";
      };

      lector.readAsDataURL(archivo);
    } else {
      vistaPrevia.style.display = "none";
    }
  }
</script>

{% endblock %}

Tickets_Project/TicketOn/templates/Organizador/Eventos_en_curso.html
{% extends 'Conex/Conex_organizador.html' %} {% block content %} {%load static%}
<link rel="stylesheet" href="{% static 'TicketOn/Organizador.css'%}" />


<style>
  
#main-nav_1 a:hover{
  font-size: 30px;
  color:#000;
  opacity: 50%;
}
#main-nav_1:hover {
  box-shadow: 0px 10px 25px #00000043;
  height: 70px;
  padding-top: 20px;
}

#main-nav_1 {
    display: flex;
    padding: 5px 5%;
    justify-content: space-between;
    box-shadow: 0px 10px 25px #00000043;
    background-color: #93c012;
    height: 60px;
    top: 0;
    position: fixed;
    width: 100%;
    transition-duration: 0.3s;
  }

  #imagenevento {
    display: block;
    margin-top: 15px;
    width: 400px;
    height: 300px;
    margin-left: auto;
    margin-right: auto;
  }

.center-container {
    text-align: center;
    margin-top: 15px;
}

.center-container h1 {
    text-align: center;
    color: #060606; 
}

#Espacio-eventos {
  display: flex;
    flex-wrap: wrap;
    justify-content: space-around; /* Otra opción: space-between */
    gap: 20px; /* Ajusta según sea necesario */
    margin: auto;
    width: 80%;
    height: fit-content;
}

.Tarjeta-evento {
  list-style-type: none;
    flex: 0 0 calc(30% - 20px); /* Ajusta el tamaño base y el espacio entre tarjetas según tus preferencias */
    text-decoration: none;
    background-color: rgb(249, 249, 249);
    border-radius: 20px;
    margin-bottom: 20px;
    box-sizing: border-box;
    display: flex; /* Agrega esta línea para establecer la dirección de fila para las imágenes */
    flex-direction: column;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.496);
}
    

.Tarjeta-evento img {
    width: 100%;
    height: 250px;
    border-radius: 20px 20px 0px 0px;
}

.Tarjeta-evento input{
    width: 50%;
    padding: 8px;
    box-sizing: border-box;
    background-color: #4caf50;
    border: none;
    padding: 10px 15px;
    font-size: 16px;
    border-radius: 4px;
    cursor: pointer;
    margin-top: 10px;
}

.Tarjeta-evento input:hover {
  background-color: #454;
    color: #fff;
    font-size: 20px;
    font-weight: bold;

}

footer{
    display: flex ;
    column-gap: 20px ;
    background-color: #1a390b;
    text-align:justify;
    text-justify:inter-word;
    width: 96%;
    padding: 30px;
    height: fit-content;
  }

  footer ul{
    color: #fff;
    margin: auto;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
  }

  footer p{
    text-decoration: none;
    font-size: 50px;
    font-weight: bold;
    color: #E5E5E5;
    font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
    transition-duration: 0.3s;
  }
</style>

<div class="center-container">
  <h1>Eventos en Curso</h1>
  {% if eventos_en_curso %}
    <div id="Espacio-eventos">
      {% for evento in eventos_en_curso %}
        <div class="Tarjeta-evento">
          <strong>{{ evento.nombre }}</strong><br />
          Lugar: {{ evento.lugar }}<br />
          Fecha: {{ evento.fecha }}<br />
          Hora: {{ evento.hora }}<br />
          Descripción: {{ evento.descripcion }}<br />
          Precio: {{ evento.precio }}<br />
          {% if evento.imagen %}
            <img id="imagenevento" src="{{ evento.imagen.url }}" alt="{{ evento.nombre }} imagen" />
          {% endif %}
        
          <form action="{% url 'TicketOn:editar_evento' evento.slug %}">
            <input type="submit" value="Editar evento">
          </form>

        </div>
      {% endfor %}
    </div>
  {% else %}
    <p>No hay eventos en curso actualmente.</p>
  {% endif %}
</div>


<footer>
  <p id="NombreTJ" href="/home/">TicketJaeger</p>
  <ul>
      <li>Telefono de atencion: 656-495-88-83<br></li>
      <li>Correo de atencion: TicketJaeger@ayuda.com<br></li>
      <li>Instagaram: @TicketJaeger<br></li>
      <li>Facebook: TicketJaeger<br></li>
  </ul>
</footer>
{% endblock %}

Tickets_Project/TicketOn/templates/Organizador/Ventas.html
{% extends 'Conex/Conex_organizador.html' %} {% block content %} {%load static%}
<link rel="stylesheet" href="{% static 'TicketOn/Organizador.css'%}" />
<h1>Ventas</h1>

{% endblock %}